export const mockProductData = [
  {
    id: "1",
    title: "Product 1",
    description: "Description for Product 1",
    price: 10,
    count: 1,
  },
  {
    id: "2",
    title: "Product 2",
    description: "Description for Product 2",
    price: 20,
    count: 2,
  },
  {
    id: "3",
    title: "Product 3",
    description: "Description for Product 3",
    price: 30,
    count: 3,
  },
  {
    id: "4",
    title: "Product 4",
    description: "Description for Product 4",
    price: 40,
    count: 4,
  },
  {
    id: "5",
    title: "Product 5",
    description: "Description for Product 5",
    price: 50,
    count: 5,
  },
  {
    id: "6",
    title: "Product 6",
    description: "Description for Product 6",
    price: 60,
    count: 6,
  },
  {
    id: "7",
    title: "Product 7",
    description: "Description for Product 7",
    price: 70,
    count: 7,
  },
  {
    id: "8",
    title: "Product 8",
    description: "Description for Product 8",
    price: 80,
    count: 8,
  },
  {
    id: "9",
    title: "Product 9",
    description: "Description for Product 9",
    price: 90,
    count: 9,
  },
  {
    id: "10",
    title: "Product 10",
    description: "Description for Product 10",
    price: 100,
    count: 10,
  },
];